### ISSUE TITLE
Dependency Management

### ISSUE THREAD

**Issue by paketb0te** [initialcommit-com/git-sim#9]
Once again, this is a great tool!

Can I interest you in using [`poetry`](https://python-poetry.org/docs/) for packaging and dependency management?

I had pretty good experiences with it, can definitely recommend.

If you prefer a simpler approach like `requirements.txt` that's fine too (but I _really_ recommend to take a look at poetry :laughing:)

(Would look something like [THAT](https://github.com/paketb0te/git-sim/tree/poetry))

**Comment by initialcommit-io** [comment]
Hi and thank you! Thx for reaching out.

Right now I'm just using entries in the `setup.py` like:

    install_requires=[
        'gitpython',
        'manim',
        'opencv-python-headless',
    ],

Which takes care of collecting everything automatically.  It looks like the `poetry.lock` file you generated breaks down every dependency and stores it. Is the benefit of this that it more or less guarantees that the build will succeed by defining specific versions of every dependency? Seems a bit messier to need to store all of this info though when most of the build dependences are nested within each other. Like, most of those dependencies come from Manim...

**Comment by paketb0te** [comment]
yeah, you only need to specify them explicitly in the `pyproject.toml` file (with constrints, if you wish, like "needs at least verion X.Y of package Z").

The file `poetry.lock` is created automatically by poetry (`poetry lock`) to pin all dependencies to fixed versions, which as you mention helps ensure that the build is reproducible / identical for everybody.

**Comment by initialcommit-io** [comment]
I see, thanks for the suggestion.  I need to learn more about `poetry` and other options and will get back to you on this one.

**Comment by initialcommit-io** [comment]
@paketb0te I'm playing around with poetry and got a similar `pyproject.toml` file to the one at your link.

Just a few questions about some extra info that is currently in the `setup.py` file which I wasn't prompted for by the interactive poetry setup:

-url
-keywords
-project_urls (homepage and source)
-entry_points

Do you know how these can be specified with poetry?

**Comment by paketb0te** [comment]
According to the [docs](https://python-poetry.org/docs/pyproject/), we can just specify those in `pyproject.toml`, e.g. `repository = "https://github.com/initialcommit-com/git-sim"`

So it would lok something like this:

```toml
[tool.poetry]
name = "git-sim"
version = "0.1.2"
description = "Simulate Git commands on your own repos by generating an image (default) or video visualization depicting the command's behavior."
authors = ["Jacob Stopak <jacob@initialcommit.io>"]
license = "MIT"
readme = "README.md"
packages = [{include = "git_sim"}]
homepage = "https://git-sim.org/"
keywords = ["git", "sim", "simulation", ...]
repository = "https://github.com/initialcommit-com/git-sim
...
```

If I understand correctly, you can define the equivalent to `entry_points` via plugins in a subsection in the `pyproject.toml` (see [docs](https://python-poetry.org/docs/pyproject/#plugins))
